// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1LEE0bJpY9nFUiJ_X63aV9QG1ZbOwxE',
    appId: '1:994398224911:web:4a1dcf4f30ccba5473997a',
    messagingSenderId: '994398224911',
    projectId: 'newappproject-f4d4e',
    authDomain: 'newappproject-f4d4e.firebaseapp.com',
    storageBucket: 'newappproject-f4d4e.firebasestorage.app',
    measurementId: 'G-0HT579TJDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIMUdxlw2sd0Kj9S3lURDBP0QiB_h6YY',
    appId: '1:994398224911:android:19c313b62f9f44e973997a',
    messagingSenderId: '994398224911',
    projectId: 'newappproject-f4d4e',
    storageBucket: 'newappproject-f4d4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSeyU4kaN8Sl-_y4vunUWNsuECKmWummY',
    appId: '1:994398224911:ios:34b7baba8f6a06a273997a',
    messagingSenderId: '994398224911',
    projectId: 'newappproject-f4d4e',
    storageBucket: 'newappproject-f4d4e.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSeyU4kaN8Sl-_y4vunUWNsuECKmWummY',
    appId: '1:994398224911:ios:34b7baba8f6a06a273997a',
    messagingSenderId: '994398224911',
    projectId: 'newappproject-f4d4e',
    storageBucket: 'newappproject-f4d4e.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt1LEE0bJpY9nFUiJ_X63aV9QG1ZbOwxE',
    appId: '1:994398224911:web:9f09556353c2a87173997a',
    messagingSenderId: '994398224911',
    projectId: 'newappproject-f4d4e',
    authDomain: 'newappproject-f4d4e.firebaseapp.com',
    storageBucket: 'newappproject-f4d4e.firebasestorage.app',
    measurementId: 'G-95EWH56W5P',
  );
}
